---
# TODO:
# * split tasks to host setup, devstack setup(per version different config)
- name: Create stack user
  user:
    name: stack
    shell: "/bin/bash"

- name: Set authorized key for stack
  authorized_key:
    user: stack
    state: present
    key: "{{ lookup('file', '/home/gibizer/.ssh/id_rsa.pub') }}"

- name: Allow stack to have passwordless sudo
  copy:
    dest: "/etc/sudoers.d/stack"
    content: |
      stack ALL=(ALL) NOPASSWD: ALL

- name: Ensure ipv6 is enabled
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: 0
    state: present
    sysctl_set: true

- name: Install python-apt to help ansible to install other packages
  package:
    name: python-apt
    state: present

- name: Install ovs
  package:
    name: openvswitch-switch
    state: present

- name: Ensure br-test for bandwidth config
  openvswitch_bridge:
    bridge: br-test
    state: present


- block:  # tasks with the stack user

    - name: Clone devstack repo
      git:
        repo: https://opendev.org/openstack/devstack.git
        version: master
        dest: "~/devstack"

    - name: Copy local.conf
      copy:
        dest: "~/devstack"
        src: "local.conf"

    - name: Copy bandwidth port create script
      copy:
        dest: "~/"
        src: "create_bandwidth_port.sh"

    - name: Unstack
      command: "./unstack.sh"
      args:
        chdir: "/home/stack/devstack"

    - name: Clean
      command: "./clean.sh"
      args:
        chdir: "/home/stack/devstack"

    - name: Stack
      command: "./stack.sh"
      args:
        chdir: "/home/stack/devstack"

    # run create_bandwidth_port

  become: yes
  become_user: stack



