[[local|localrc]]
ADMIN_PASSWORD=admin
DATABASE_PASSWORD=$ADMIN_PASSWORD
RABBIT_PASSWORD=$ADMIN_PASSWORD
SERVICE_PASSWORD=$ADMIN_PASSWORD

enable_plugin neutron https://github.com/openstack/neutron.git


LIBS_FROM_GIT="openstacksdk,neutron-lib,os-vif,os-traits,oslo-messaging,oslo-service,oslo-config"

ENABLED_SERVICES=n-cpu
ENABLED_SERVICES+=,placement-client,neutron-ovn-agent

LOGFILE=$DEST/logs/stack.sh.log

USE_PYTHON3=True

DEVSTACK_PARALLEL=True

OFFLINE=False
RECLONE=True

# pointing to the mounted dir for git repos
GIT_BASE="file:///vagrant/gitcache"

DATABASE_TYPE=mysql
SERVICE_HOST=???
MYSQL_HOST=$SERVICE_HOST
RABBIT_HOST=$SERVICE_HOST
GLANCE_HOSTPORT=$SERVICE_HOST:9292
NOVNCPROXY_URL="http://$SERVICE_HOST:6080/vnc_lite.html"
VNCSERVER_LISTEN=$HOST_IP
VNCSERVER_PROXYCLIENT_ADDRESS=$VNCSERVER_LISTEN

VIRT_DRIVER=fake
NUMBER_FAKE_NOVA_COMPUTE=5

NOVA_NUM_CELLS=2
FAKE_NOVA_COMPUTE_DISTRIBUTE_CELLS=true

# neutron.conf
[[post-config|/etc/neutron/neutron.conf]]
[DEFAULT]
service_plugins = router, placement, qos, segments
[placement]
project_domain_name = Default
project_name = service
user_domain_name = Default
password = admin
username = nova
auth_url = http://$SERVICE_HOST/identity
auth_type = password

# ml2_conf.ini
[[post-config|/etc/neutron/plugins/ml2/ml2_conf.ini]]
[agent]
tunnel_types = vxlan

[[post-config|/etc/neutron/dhcp_agent.ini]]
[DEFAULT]
enable_isolated_metadata = True

force_metadata = False

[[post-config|/etc/neutron/l3_agent.ini]]
[DEFAULT]
enable_metadata_proxy = True


## nova.conf
[[post-config|/etc/nova/nova.conf]]

[DEFAULT]
# restore default as devstack overrides this to a super high value
#service_down_time = 60
#report_interval = 10

[oslo_messaging_notifications]
driver = messagingv2
driver = log
transport_url = rabbit://stackrabbit:admin@$SERVICE_HOST:5672/

[compute]
instance_usage_audit = true

[notifications]
notification_format = both
notify_on_state_change = vm_and_task_state
bdms_in_notifications = true

[filter_scheduler]
enabled_filters = ComputeFilter, ComputeCapabilitiesFilter, ImagePropertiesFilter, ServerGroupAntiAffinityFilter, ServerGroupAffinityFilter, PciPassthroughFilter, NUMATopologyFilter
pci_in_placement = true

[pci]
report_in_placement = true
