[[local|localrc]]
ADMIN_PASSWORD=admin
DATABASE_PASSWORD=$ADMIN_PASSWORD
RABBIT_PASSWORD=$ADMIN_PASSWORD
SERVICE_PASSWORD=$ADMIN_PASSWORD

enable_plugin neutron https://github.com/openstack/neutron.git


LIBS_FROM_GIT="python-neutronclient,openstacksdk,python-novaclient,osc-placement,neutron-lib,os-vif,os-traits,oslo-messaging,oslo-service,oslo-config,rally,rally-openstack"

enable_service key

enable_service n-api
enable_service n-cpu
enable_service n-cond
enable_service n-sch
enable_service n-novnc
enable_service n-cauth
enable_service n-api-meta
enable_service placement-api
enable_service placement-client

enable_service ovn-northd
enable_service ovn-controller

enable_service q-svc

disable_service q-ovn-metadata-agent

disable_service q-agt
disable_service q-l3
disable_service q-dhcp
disable_service q-meta

disable_service cinder c-sch c-api c-vol
disable_service horizon
disable_service tempest

# At the moment the osc optimization can only be enabled if osc is not
# installed from git
enable_service openstack-cli-server

#enable_plugin osprofiler
#OSPROFILER_COLLECTOR=sqlalchemy
#OSPROFILER_HMAC_KEYS=admin
#OSPROFILER_TRACE_SQLALCHEMY=True

LOGFILE=$DEST/logs/stack.sh.log

USE_PYTHON3=True

DEVSTACK_PARALLEL=True


OFFLINE=False
RECLONE=True

# pointing to the mounted dir for git repos
GIT_BASE="file:///vagrant/gitcache"

VIRT_DRIVER=fake
NUMBER_FAKE_NOVA_COMPUTE=5

NOVA_NUM_CELLS=2
FAKE_NOVA_COMPUTE_DISTRIBUTE_CELLS=true

enable_plugin rally-openstack https://opendev.org/openstack/rally-openstack

enable_service dstat
enable_service memory_tracker

# ml2_conf.ini
[[post-config|/etc/neutron/plugins/ml2/ml2_conf.ini]]
[agent]
tunnel_types = vxlan

[[post-config|/etc/neutron/dhcp_agent.ini]]
[DEFAULT]
enable_isolated_metadata = True

force_metadata = False

[[post-config|/etc/neutron/l3_agent.ini]]
[DEFAULT]
enable_metadata_proxy = True


## nova.conf
[[post-config|/etc/nova/nova.conf]]

[DEFAULT]
# restore default as devstack overrides this to a super high value
#service_down_time = 60
#report_interval = 10

[oslo_messaging_notifications]
driver = messagingv2
driver = log
transport_url = rabbit://stackrabbit:admin@127.0.0.1:5672/

[compute]
instance_usage_audit = true

[notifications]
notification_format = both
notify_on_state_change = vm_and_task_state
bdms_in_notifications = true

[filter_scheduler]
enabled_filters = ComputeFilter, ComputeCapabilitiesFilter, ImagePropertiesFilter, ServerGroupAntiAffinityFilter, ServerGroupAffinityFilter, PciPassthroughFilter, NUMATopologyFilter
pci_in_placement = True

[pci]
report_in_placement = true


## nova_cell1.conf
[[post-config|/etc/nova/nova_cell1.conf]]

[oslo_messaging_notifications]
driver = messagingv2
driver = log
transport_url = rabbit://stackrabbit:admin@127.0.0.1:5672/

[compute]
instance_usage_audit = true

[notifications]
notification_format = both
notify_on_state_change = vm_and_task_state
bdms_in_notifications = true
