bus/pci/devices/0000:06:*/numa_node = 0
bus/pci/devices/0000:07:*/numa_node = 0
bus/pci/devices/0000:08:*/numa_node = 0
bus/pci/devices/0000:09:*/numa_node = 0

bus/pci/devices/0000:0a:*/numa_node = 1
bus/pci/devices/0000:0b:*/numa_node = 1
bus/pci/devices/0000:0c:*/numa_node = 1
bus/pci/devices/0000:0d:*/numa_node = 1
