---
- name: Update grub
  become: true
  ansible.builtin.command: /usr/sbin/update-grub
  changed_when: true

- name: Update initramfs
  become: true
  ansible.builtin.command: /usr/sbin/update-initramfs -u -k all
  changed_when: true

- name: Restart VM
  ansible.builtin.include_tasks:
    roles/devstack-sriov/tasks/restart_vm.yaml
