---
- name: Set apt caching proxy
  when: apt_cache_proxy is defined
  become: true
  ansible.builtin.copy:
    content: |
      Acquire::http { Proxy "{{ apt_cache_proxy }}"; }
    dest: /etc/apt/apt.conf.d/proxy
    mode: '0644'

- name: Update apt cache and upgrade packages
  become: true
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ packages_present }}"

- name: Remove packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ packages_absent }}"
