---
- name: Create stack user
  become: true
  ansible.builtin.user:
    name: stack
    shell: "/bin/bash"

- name: Set authorized key for stack
  become: true
  ansible.posix.authorized_key:
    user: stack
    state: present
    key: "{{ lookup('file', '{{ ssh_access_pub_key }}') }}"

- name: Allow stack to have passwordless sudo
  become: true
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/stack"
    content: |
      stack ALL=(ALL) NOPASSWD: ALL
    owner: root
    group: root
    mode: '0644'

  # NOTE(gibi): it would be better to use the idmap tag for virtiofs in the
  # libvirt XML but vagrant-libvirt provider does not expose it yet
- name: Mark /vagrant/gitcache as safe git directory
  become: true
  become_user: stack
  community.general.git_config:
    name: safe.directory
    value: "*"
    scope: global
