---

- name: Generate compute_nodes.yaml
  delegate_to: localhost
  vars:
    template:
      services:
        libvirt:
          start_command: 'systemctl start libvirtd'
          stop_command: 'systemctl stop libvirtd'
          mask_command: 'systemctl mask libvirtd'
          unmask_command: 'systemctl unmask libvirtd'
        nova-compute:
          config_path: '/etc/nova/nova-cpu.conf'
          start_command: 'systemctl start devstack@n-cpu'
          stop_command: 'systemctl stop devstack@n-cpu'
  ansible.builtin.set_fact:
    compute_nodes: "{{ (compute_nodes | default({})) | combine({item: template}) }}"
  with_items: "{{ groups['all'] }}"

- name: Write compute_nodes.yaml
  become: true
  become_user: stack
  ansible.builtin.copy:
    dest: /home/stack/compute_nodes.yaml
    content: "{{ compute_nodes | to_json }}"
    owner: stack
    group: stack
    mode: '0644'

- name: Install whitebox plugin to tempest venv
  become: true
  become_user: stack
  ansible.builtin.pip:
    name: file:///opt/stack/whitebox-tempest-plugin
    virtualenv: /opt/stack/tempest/.tox/tempest/

- name: Amend tempest config with whitebox config
  become: true
  become_user: stack
  community.general.ini_file:
    path: /opt/stack/tempest/etc/tempest.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: '0666'
  loop:
    - { section: 'compute',
        option: 'min_compute_nodes', value: '{{ groups["all"] | length }}'}
    - { section: 'whitebox',
        option: 'nodes_yaml', value: '/home/stack/compute_nodes.yaml'}
    - { section: 'whitebox',
        option: 'ctlplane_ssh_private_key_path', value: '/home/stack/.ssh/id_ed25519'}
    - { section: 'whitebox',
        option: 'ctlplane_ssh_username', value: 'stack'}
    - { section: 'whitebox-hardware',
        option: 'sriov_physnet', value: 'physnet2'}
    - { section: 'whitebox-hardware',
        option: 'sriov_vlan_id', value: '101'}
    - { section: 'whitebox-hardware',
        option: 'sriov_vnic_type', value: 'direct'}
    - { section: 'whitebox-hardware',
        option: 'sriov_nic_vendor_id', value: '8086'}
    - { section: 'whitebox-hardware',
        option: 'sriov_vf_product_id', value: '10ca'}
    - { section: 'whitebox-hardware',
        option: 'physnet_numa_affinity', value: '0'}
